name: symphony
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  get: ^4.6.5
  flutter_secure_storage: ^5.0.2
  blur_bottom_bar: ^1.0.3
  url_launcher: ^6.1.5
  video_player: ^2.4.5
  audio_service: ^0.18.7
  just_audio: ^0.9.28
  custom_sliding_segmented_control: ^1.7.1
  audio_session: ^0.1.10
  dio: ^4.0.6
  youtube_explode_dart: ^1.12.0
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  flutter_youtube_downloader: ^0.0.5
  youtube_dl: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
