name: symphony
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  get: ^4.6.5
  flutter_secure_storage: ^5.0.2
  blur_bottom_bar: ^1.0.3
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
  video_player: ^2.4.5
  audio_service: ^0.18.7
  just_audio: ^0.9.28
  custom_sliding_segmented_control: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
